package com.github.chronos2011.fretter.domain.solver;

import java.util.List;

import com.github.chronos2011.fretter.domain.Board;
import com.github.chronos2011.fretter.domain.Fingering;
import com.github.chronos2011.fretter.options.ApplicationOptions.Operation;

/**
 * Class Solution defines a solution for a specific mode of {@link Operation}. A Solution either includes a
 * {@link Board} or a list of {@link Fingering}s (in case of {@link Operation#CHORD}). It might as well include warnings
 * or hints created from a {@link Solver}.
 */
public class Solution {
	/** {@link Board} that was found during solving */
	public final Board board;
	/** List of {@Fingering}s that was found during solving (in case of {@link Operation#CHORD}) */
	public final List<Fingering> fingerings;
	/** List of warnings generated by the {@link Solver} */
	public final List<String> warnings;
	/** List of hints generated by the {@link Solver} */
	public final List<String> hints;

	public Solution(Board board, List<Fingering> fingerings, List<String> warnings, List<String> hints) {
		this.board = board;
		this.fingerings = fingerings;
		this.warnings = warnings;
		this.hints = hints;
	}
}
